coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

ignore:
  - "**/*_test.go"
  - "**/mock_*.go"
  - "cmd/**"
